(define
	(problem instance2)
	(:domain emergency-handling)
	(:objects 
		a1 a2 - agent
		c1 c2 - carrier
		b1 b2 b3  - box
		place1 place2 place3 place4 - place
		p1 p2 p3 p4 p5 p6 - person
		food tool medicine - content
		depot  - depot
		l1 l2 l3 l4 l5 - emergencyposition
	)

	(:init 
		(empty b1)
		(empty b2)
		(empty b3)
		(loadable b1)
		(loadable b2)
		(loadable b3)
		(of place1 c1)
		(of place2 c1)
		(of place3 c2)
		(of place4 c2)
		(available place1 c1)
		(available place2 c1)
		(available place3 c2)
		(available place4 c2)
		(at a1 depot)
		(at a2 depot)
		(at c1 depot)
		(at c2 depot)
		(at b1 depot)
		(at b2 depot)
		(at b3 depot)
		(at p1 l1)
		(at p2 l1)
		(at p3 l2)
		(at p4 l3)
		(at p5 l4)
		(at p6 l5)
		(need p1 food)
		(need p1 tool)
		(need p2 medicine)
		(need p3 medicine)
		(need p4 medicine)
		(need p4 food)
		(need p5 food)
		(need p5 tool)
		(need p5 medicine)
		(need p6 food)
		(need p6 tool)
		(need p6 medicine)
		(= (weight food) 5)
		(= (weight tool) 10)
		(= (weight medicine) 3)
		(= (box-weight b1) 0)
		(= (box-weight b2) 0)
		(= (box-weight b3) 0)
		(= (carrier-weight c1) 0)
		(= (carrier-weight c2) 0)
		(= path-cost 0)
	)

	(:goal (and  (not (need p1 food))
			(not (need p1 tool))
			(not (need p2 medicine))
			(not (need p3 medicine))
			(not (need p4 medicine))
			(not (need p4 food))
			(not (need p5 food))
			(not (need p5 tool))
			(not (need p5 medicine))
			(not (need p6 food))
			(not (need p6 tool))
			(not (need p6 medicine))
		)
	)

	(:metric minimize (path-cost)
    )
)